# -*- coding: utf-8 -*-
"""Decision Tree Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tU0tSW-bgqXbRREAazqt1COB7y-tL0ly
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, accuracy_score
from sklearn.pipeline import Pipeline

# Import functions from preprocessing file
from preprocessing import load_data, get_preprocessor
from sklearn.model_selection import cross_validate

# Load train and test data
X_train_full, y_train_full = load_data('train.csv', data_dir='data/raw')
X_test_final, y_test_final = load_data('test.csv', data_dir='data/raw')

# Get the preprocessor
preprocessor = get_preprocessor(X_train_full)

# Model setup
# Use min_samples_split=20 to stop the tree from overfitting
dt_model = DecisionTreeClassifier(random_state=42, min_samples_split=20)

clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', dt_model)])

# Cross Validation, using stratified kfold to keep class balance
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = cross_validate(
    clf, X_train_full, y_train_full, 
    cv=cv, 
    scoring={'accuracy': 'accuracy', 'roc_auc': 'roc_auc'}
)

print(f"--- 5-Fold Cross-Validation Results ---")
print(f"Mean Accuracy: {cv_results['test_accuracy'].mean():.4f}")
print(f"Mean AUC: {cv_results['test_roc_auc'].mean():.4f}")

# Evaluation on test data

print("\nTraining final model on full Train set and evaluating on Test set...")
clf.fit(X_train_full, y_train_full)

y_pred_final = clf.predict(X_test_final)
final_accuracy = accuracy_score(y_test_final, y_pred_final)

print(f"--- FINAL TEST SET RESULTS ---")
print(f"Accuracy on test.csv: {final_accuracy:.4f}")

# Global Feature Importance
# Reconstruct feature names
numerical_features = X_train_full.select_dtypes(include=['number']).columns.tolist()
ordinal_features = ['Class']
# Get one-hot names from the pipeline
nominal_features = ['Gender', 'Customer Type', 'Type of Travel']
cat_names = clf.named_steps['preprocessor'].named_transformers_['cat']['encoder'].get_feature_names_out(nominal_features).tolist()

feature_names = numerical_features + ordinal_features + cat_names

importances = clf.named_steps['classifier'].feature_importances_
feat_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)

# Plotting global top 10
plt.figure(figsize=(10, 6))
feat_imp.head(10).plot(kind='barh', color='#4c72b0')
plt.title('Top 10 Drivers of Satisfaction (Global Model)')
plt.xlabel('Relative Importance (Gini Impurity reduction)')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('dt_feature_importance.png')
print("Saved dt_feature_importance.png")

# Confusion Matrix and ROC (on test data)
cm = confusion_matrix(y_test_final, y_pred_final)
print("\n--- Confusion Matrix (Text) ---")
cm_df = pd.DataFrame(cm,
                     index=['Actual: Neutral/Dissatisfied', 'Actual: Satisfied'],
                     columns=['Pred: Neutral/Dissatisfied', 'Pred: Satisfied'])
print(cm_df)
print("-" * 30)

# Confusion Matrix Plot
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix (Test Set)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.savefig('dt_confusion_matrix.png')
print("Saved dt_confusion_matrix.png")

# ROC Curve
y_pred_proba_test = clf.predict_proba(X_test_final)[:, 1]
fpr, tpr, _ = roc_curve(y_test_final, y_pred_proba_test)
final_auc = roc_auc_score(y_test_final, y_pred_proba_test)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {final_auc:.2f}')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.title('ROC Curve (Test Set)')
plt.legend(loc="lower right")
plt.savefig('dt_roc_curve.png')
print("Saved dt_roc_curve.png")

# Tree Visualization & Rules (Depth 3)
# Fitting a smaller tree
clf_small = Pipeline(steps=[('preprocessor', preprocessor),
                            ('classifier', DecisionTreeClassifier(max_depth=3, random_state=42))])
clf_small.fit(X_train_full, y_train_full)

# Clean up feature names for the visualization
cat_names_cleaned = [c.replace('Type of Travel_', '').replace('Customer Type_', '').replace('Gender_', '') for c in cat_names]
all_feature_names = numerical_features + ['Class'] + cat_names_cleaned

# Plot the tree image
plt.figure(figsize=(25, 12))
plot_tree(clf_small.named_steps['classifier'],
          feature_names=all_feature_names,
          class_names=['Neutral/Dissatisfied', 'Satisfied'],
          filled=True,
          rounded=True,
          fontsize=12,
          impurity=False)

plt.title("Decision Tree Logic (Top 3 Levels)\n<--- LEFT is True (Yes)  |  RIGHT is False (No) --->", fontsize=16)
plt.savefig('decision_tree_viz.png')
print("Saved decision_tree_viz.png")

# Print the text rules
r = export_text(clf_small.named_steps['classifier'], feature_names=all_feature_names)
r = r.replace("class: 0", "class: Neutral/Dissatisfied")
r = r.replace("class: 1", "class: Satisfied")

print("\n--- Decision Tree Rules (Top 3 Levels) ---")
print(r)

# Subgroup analysis (business vs eco)
# Create a temporary dataframe that combines X and y so we can filter easily
df_full = X_train_full.copy()
df_full['satisfaction'] = y_train_full


def get_importance_for_subset(filter_col, filter_value):
    subset = df_full[df_full[filter_col] == filter_value]
    if len(subset) == 0:
        return None

    y_sub = subset['satisfaction']
    X_sub = subset.drop('satisfaction', axis=1)

    # New model
    local_preprocessor = get_preprocessor(X_train_full)
    local_model = DecisionTreeClassifier(random_state=42, min_samples_split=20)

    local_clf = Pipeline(steps=[('preprocessor', local_preprocessor),
                                ('classifier', local_model)])

    local_clf.fit(X_sub, y_sub)

    # Get feature names again
    local_cat_names = local_clf.named_steps['preprocessor'].named_transformers_['cat']['encoder'].get_feature_names_out(nominal_features).tolist()
    local_cat_names = [c.replace('Type of Travel_', '').replace('Customer Type_', '').replace('Gender_', '') for c in local_cat_names]
    local_feat_names = numerical_features + ordinal_features + local_cat_names

    imps = local_clf.named_steps['classifier'].feature_importances_
    return pd.Series(imps, index=local_feat_names)

# Comparison 1: Class
imp_bus = get_importance_for_subset('Class', 'Business')
imp_eco = get_importance_for_subset('Class', 'Eco')
imp_plus = get_importance_for_subset('Class', 'Eco Plus')

df_class_comp = pd.DataFrame({'Business': imp_bus, 'Economy': imp_eco, 'Eco Plus': imp_plus})
df_class_comp = df_class_comp.sort_values(by='Business', ascending=False).head(8)

df_class_comp.plot(kind='bar', figsize=(14, 6), width=0.8, color=['#4c72b0', '#dd8452', '#55a868'])
plt.title('Feature Importance by Travel Class')
plt.ylabel('Relative Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('subgroup_class_comparison.png')
print("Saved subgroup_class_comparison.png")

# Generate Comparison 2: Travel Type
imp_biz_travel = get_importance_for_subset('Type of Travel', 'Business travel')
imp_personal = get_importance_for_subset('Type of Travel', 'Personal Travel')

df_type_comp = pd.DataFrame({'Business Travel': imp_biz_travel, 'Personal Travel': imp_personal})
df_type_comp = df_type_comp.sort_values(by='Business Travel', ascending=False).head(8)

df_type_comp.plot(kind='bar', figsize=(12, 6), width=0.8, color=['#8172b3', '#c44e52'])
plt.title('Feature Importance by Type of Travel')
plt.ylabel('Relative Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('subgroup_type_comparison.png')
print("Saved subgroup_type_comparison.png")