# -*- coding: utf-8 -*-
"""Shared Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkSScyGm5-O1BOhJV7x84wglA_d_G-de
"""

import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Helper function to load data
def load_data(file_name, data_dir='data/raw'):
    """Load data from CSV file. Looks in data_dir for the file."""
    file_path = Path(data_dir) / file_name
    df = pd.read_csv(file_path)

    # Drop the id columns, we don't need them for prediction
    cols_to_drop = ['Unnamed: 0', 'id']
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors='ignore')

    # Separate target variable
    if 'satisfaction' in df.columns:
        X = df.drop('satisfaction', axis=1)
        # Encoding 1 = satisfied, 0 = neutral or dissatisfied
        y = df['satisfaction'].apply(lambda x: 1 if x == 'satisfied' else 0)
    else:
        # Unlabeled data just return X
        X = df
        y = None

    return X, y

# Function to get the pipeline
def get_preprocessor(X_sample):
    # Define column groups
    numerical_features = X_sample.select_dtypes(include=['number']).columns.tolist()
    ordinal_features = ['Class']
    nominal_features = ['Gender', 'Customer Type', 'Type of Travel']

    # Verify columns exist
    for col in ordinal_features + nominal_features:
        if col not in X_sample.columns:
            raise ValueError(f"Column {col} missing from input data")

    # For numerical features: impute missing delay values with median
    # and scale using StandardScaler because of outliers
    numerical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    # For 'Class' feature: ordinal encoding (Economy < Eco Plus < Business)
    ordinal_transformer = Pipeline(steps=[
        ('encoder', OrdinalEncoder(categories=[['Eco', 'Eco Plus', 'Business']]))
    ])

    # For nominal features: one-hot encoding
    categorical_transformer = Pipeline(steps=[
        ('encoder', OneHotEncoder(drop='first', handle_unknown='ignore'))
    ])

    # Combine everything
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numerical_transformer, numerical_features),
            ('ord', ordinal_transformer, ordinal_features),
            ('cat', categorical_transformer, nominal_features)
        ])

    return preprocessor